### ISSUE TITLE
Background overlay not appearing

### ISSUE THREAD

**Issue by Braunson** [lipis/bootstrap-sweetalert#17]
The alert appears but no faded black/grey overlay appears at all so the alert blends in on a white background.

**Comment by jrichview** [comment]
I'm having this issue. Could you please clarify what you updated? I have latest of this plugin.

**Comment by jrichview** [comment]
Follow-up: I was using swal from within a button click event on a bootstrap modal. I set a style override for sweet-overlay to z-index 2000 and it seems to be resolved.
