### ISSUE TITLE
Could you include the last version of sweetalert?

### ISSUE THREAD

**Issue by papasax** [lipis/bootstrap-sweetalert#20]
This big bug has been corrected:
https://github.com/t4t5/sweetalert/commit/364d83d8a4fd3f8590de0aff492a8e2acee2df29

Thanks

**Comment by lipis** [comment]
yes.. quite a bit of a task.. but I'll have to do it soonish..! Thanks

**Comment by lipis** [comment]
It's basically #11

**Comment by papasax** [comment]
I just refreshed my project. All is fine. Thanks.
