### ISSUE TITLE
Random failed on page with pdfjs viewer

### ISSUE THREAD

**Issue by thangngoc89** [lipis/bootstrap-sweetalert#21]
On the same page, if there is a pdfjs ( http://mozilla.github.io/pdf.js/ ) viewer in iframe, sweetalert randomly failed with no reason. (I repeat this action about 20 times, it failed 13 times).

I don't know which version I should provide for you. You can ask me if you need any further information.
Stack trace:

Cannot read property 'querySelector' of null (this line https://github.com/lipis/bootstrap-sweetalert/blob/master/lib/sweet-alert.js#L458 )
setParameters (this line https://github.com/lipis/bootstrap-sweetalert/blob/master/lib/sweet-alert.js#L458 )
window.sweetAlert.window.swal (this line https://github.com/lipis/bootstrap-sweetalert/blob/master/lib/sweet-alert.js#L258 )

My page js dependency
```
            'bower_components/jquery/dist/jquery.js',
            'bower_components/bootstrap/dist/js/bootstrap.js',
            'bower_components/wow/dist/wow.min.js',
            'bower_components/sticky-kit/jquery.sticky-kit.js',
            'bower_components/toastr/toastr.js',
            'bower_components/bootstrap-sweetalert/lib/sweet-alert.js',
            'bower_components/pace/pace.js',
            'bower_components/jquery-unveil/jquery.unveil.js',
            'bower_components/jquery-form/jquery.form.js',
            'bower_components/selectize/dist/js/standalone/selectize.js'
            'bower_components/FroalaWysiwygEditor/js/froala_editor.min.js',
            'bower_components/FroalaWysiwygEditor/js/langs/vi.js',
            'bower_components/FroalaWysiwygEditor/js/plugins/colors.min.js'
```
I know it is a heavy js page, but I don't have a clue why it fails randomly

**Comment by alekitto** [comment]
@thangngoc89 Could you tell us if the issue is still present for the `master` branch version?

**Comment by thangngoc89** [comment]
@alekitto I don't even remember why do I created this issue. So I close this now.
