### ISSUE TITLE
Bootstrap 3 changed 'error' -> 'danger' (i.e. btn-danger)

### ISSUE THREAD

**Issue by CreativelyCloudy** [lipis/bootstrap-sweetalert#35]
Hi,

Having a blast with this.  Thanks for all the hard work.

Is there a BS3 version in the mix/coming?

Thanks.  Jeff.

**Comment by lipis** [comment]
Feel free to create a PR.

**Comment by alekitto** [comment]
BS3 classes are fully supported. The example page shows how to create a dialog with `btn-danger` class on the confirmation button
