### ISSUE TITLE
Dynamic HTML inside SweetAlert

### ISSUE THREAD

**Issue by andreiculda** [lipis/bootstrap-sweetalert#37]
When adding dynamic HTML like a bootstrap tablist with tables and other html components inside, the Sweet alert is not centered on the screen.
![image](https://cloud.githubusercontent.com/assets/10087545/7831276/d6386a5c-045d-11e5-9d84-28a4bb4203f5.png)

i declared html content as:

``` javascript
var htmlcontent = '<ul class="nav nav-pills" role="tablist">' +
                             '<li role="presentation" class="active"><a href="#POCInfo" data-toggle="tab">Details</a></li>' +
                            '<li role="presentation" >' +
                                   '<a href="#Questionnaires" data-toggle="tab">' +
                                    '<span class="label label-success"> ' + markers[z].QuestionnairesCount + '</span>' +
                                         ' Questionnaires' +
                                   '</a>' +
                              '</li>' +
                               '<li role="presentation" class="disabled"><a href="#" >Orders</a></li>' +
                            '</ul>' + .......
```

and I called SweetAlert like this:

``` javascript
swal({
     title: markers[z].Name + ' visit on ' + markers[z].VisitDate,
     text: htmlcontent,
     html: true
});
```

Do you have a solution for this or is there something i'm doing wrong?

**Comment by andreiculda** [comment]
I forgot to mention that I modified the CSS also. I put width to auto, as the AweetAlert default width was not working with what I wanted:
![image](https://cloud.githubusercontent.com/assets/10087545/7831668/a46e76f2-0461-11e5-8a46-88abf66a80ab.png)

**Comment by codrut** [comment]
Andrei, you have to dynamically update the margins of the alert also when you use dynamic width content inside the alert container.
After you generate the dynamic content, just calculate the width and set `margin-left: -(newWidth)/2`
