### ISSUE TITLE
TypeError: callee may not be accessed on strict mode functions

### ISSUE THREAD

**Issue by migig** [lipis/bootstrap-sweetalert#39]
The error is:
`TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`

The source of the error is `arguments.callee` twice as seen below:
````javascript
(function () {
  if (document.readyState === "complete" || document.readyState === "interactive" && document.body) {
    sweetAlertInitialize();
  } else {
    if (document.addEventListener) {
      document.addEventListener('DOMContentLoaded', function factorial() {
        document.removeEventListener('DOMContentLoaded', arguments.callee, false);  // <----- BUG
        sweetAlertInitialize();
      }, false);
    } else if (document.attachEvent) {
      document.attachEvent('onreadystatechange', function() {
        if (document.readyState === 'complete') {
          document.detachEvent('onreadystatechange', arguments.callee);  // <----- BUG
          sweetAlertInitialize();
        }
      });
    }
  }
})();
````

The ["parent" sweetalert library also had this problem](https://github.com/t4t5/sweetalert/pull/250), but it's been fixed long ago. How do we deal with it for this "sub" project?

Looks like a simple fix, just to change to the function name. I'd do it, but not familiar with git.

**Comment by lipis** [comment]
Submit a PR.. you can simply edit it online and it will guide you through..

**Comment by migig** [comment]
Not that straightfoward, I accidentally created a PR on the base project, not sure how to remove it! :stuck_out_tongue_closed_eyes:

**Comment by lipis** [comment]
Just close it.. :)

**Comment by migig** [comment]
@lipis I'm trying to "fork" your repo, and it keeps forking the parent one, not this one. :stuck_out_tongue_winking_eye: 

The code I want to commit is [exactly that in the fix in the parent project](https://github.com/t4t5/sweetalert/pull/250). Can I reference it somehow?

**Comment by migig** [comment]
@lipis I managed [to do it](https://github.com/lipis/bootstrap-sweetalert/pull/40)! Have a look and tell me what you think...

At some point we should upgrade the rest of the code to match the parent library, but for now this fix is needed.
