### ISSUE TITLE
Backdrop block not working over bootstrap modal.

### ISSUE THREAD

**Issue by carlos0202** [lipis/bootstrap-sweetalert#4]
First of all, i want to say thank you for this great project, its very useful and the look and feel of the alerts. The only problem that i'm facing now, its that the sweetalerts doesnt block input from previuosly openned modals. Would be nice to add a general backdrop block to block input of focus of everyone else in the dom, including the bootstrap modals.

Thank you for all the effort on this project, and i hope that this little issue get solved. (Sorry for my bad english).

**Comment by rqx110** [comment]
same problem +1
