### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by Garito** [lipis/bootstrap-sweetalert#43]
Hi!
Giving the fact that the queryselector bug has a month, I wonder if this library is actively maintained

If it isn't, will be more honest to indicate it clearly to avoid people losting their time

Thanks!

**Comment by lipis** [comment]
I don't have much time to maintain it at the moment.. if anyone can sync with the latest would be super awesome!

**Comment by Garito** [comment]
Tell that in the readme file, be honest (no offense) and someone will know he could help

Besides that: I understand that you port the original library to bootstrap but lots of parts of the code has no sense giving the fact that jQuery is mandatory with Bootstrap (I think in hasClass function at line 41, for instance)

For my part, sorry, I'm looking for another library since I can't help here (I have work for 4 people but I only have 2 arms and a half of a brain)

**Comment by lipis** [comment]
I updated the README.md :/

**Comment by Garito** [comment]
Thanks so much!
Will try to do my best too
Hope we will be lucky enought
