### ISSUE TITLE
Property 'animation' is not working

### ISSUE THREAD

**Issue by ipolevoy** [lipis/bootstrap-sweetalert#47]
I tried the standard SA, and there it is working, but when I use bootstrap-sweetalert, it is ignored. No matter what value I supply, such as 'slide-from-bottom', the modal is popped up with the same exact double pop effect. 

Here is the sources of the entire HTML page: https://gist.github.com/ipolevoy/9dc5955d17cd42d805da

Any help is appreciated!

**Comment by alekitto** [comment]
@ipolevoy animations from standard SweetAlert have been ported to this project.
Can you tell us if this issue is still present?

**Comment by lipis** [comment]
lets close it and if needed @ipolevoy will reopen..

**Comment by ipolevoy** [comment]
@alekitto I had  to switch to standard Bootstrap modals, so not sure if this is still an issue.
