### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by alekitto** [lipis/bootstrap-sweetalert#56]
It is probably time to tag a new release
In my opinion it should be a major version, considering the big changes when syncing to the original sweetalert.

@lipis What do you think about this?

**Comment by lipis** [comment]
maybe even 1.0.0?

**Comment by alekitto** [comment]
Exactly what i had in mind

**Comment by lipis** [comment]
Update the package.json, tag and I'll publish it..

**Comment by lipis** [comment]
If you like.. you can also put these two little fellas: https://github.com/lipis/flag-icon-css#flag-icon-css

**Comment by lipis** [comment]
<img width="286" alt="screen shot 2016-05-26 at 15 49 17" src="https://cloud.githubusercontent.com/assets/125676/15576715/733d44e2-2359-11e6-8f65-165de2d063c0.png">

**Comment by alekitto** [comment]
Ok, done

**Comment by lipis** [comment]
https://www.npmjs.com/package/bootstrap-sweetalert

**Comment by lipis** [comment]
thanks!
