### ISSUE TITLE
npm install fails when grunt is not installed

### ISSUE THREAD

**Issue by mwanji** [lipis/bootstrap-sweetalert#57]
Here's the message I get, on Windows 10:

`Failed at the bootstrap-sweetalert@1.0.0 install script 'grunt compile'.

**Comment by alekitto** [comment]
Indeed! You're right, the reference to grunt in the `install` script needs to be removed...

**Comment by ashishtilara** [comment]
+1

**Comment by ashishtilara** [comment]
Is it possible to release this change, so the library can be used with latest version please.

Thank you.

**Comment by clarkewing** [comment]
+1

**Comment by lipis** [comment]
just released 1.0.1
