### ISSUE TITLE
how to show alert on alert?

### ISSUE THREAD

**Issue by thearabbit** [lipis/bootstrap-sweetalert#60]
I would like to show alert on alert (multiple).
Could example.

**Comment by lipis** [comment]
what do you mean?

**Comment by thearabbit** [comment]
I would like to show multi popup alert.

**Comment by lipis** [comment]
As if one alert is not already enough! :P

Not sure if that something that most people would want.. but either case I think it should go to the parent project.. https://github.com/t4t5/sweetalert/issues

this is mainly a wrapper for Bootstrap..
