### ISSUE TITLE
Swal after each other

### ISSUE THREAD

**Issue by dud3** [lipis/bootstrap-sweetalert#61]
The second one overwrite the first one.

```js
swal({
            title: "Note",
            text: "Blah",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
          });
```

```js
swal({
            title: "Note 2",
            text: "Blah",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
          });
```

On the other hand if we have our usual simple alert, we can easily do `alert('a'); alert('b')` and they'll work properly.

**Comment by lipis** [comment]
If anything you should most likely ask this in the original project and we'll sync it back here https://github.com/t4t5/sweetalert

**Comment by dud3** [comment]
Funky enough the original repo seem to be out of date, meh I'd easier build my own stuff.

**Comment by lipis** [comment]
some things don't last forever :/
