### ISSUE TITLE
after click cancle or other button, modal will not fit the modal frame use google chrom

### ISSUE THREAD

**Issue by satsuya0114** [lipis/bootstrap-sweetalert#67]
after click cancle or other button, modal will not fit the modal frame 

chrom version 57.0.2987.133 (64-bit windows)

![image](https://cloud.githubusercontent.com/assets/9620934/25987603/4e4fa4da-3727-11e7-85b3-ed163b9372de.png)

![image](https://cloud.githubusercontent.com/assets/9620934/25987649/797e000c-3727-11e7-9382-496a9bd366dc.png)

**Comment by alekitto** [comment]
Seems more a browser render issue.
I can't reproduce it on chrome 58.
